### ISSUE TITLE
Body Alignment Signature Creation

### ISSUE THREAD

**Issue by kbarmstrong-usgs** [mjperez-usgs/identifrog#12]
If the frog's nose is clicked before the vent in step 1 of signature creation (Body Alignment) the image is rotated the wrong way for the next step. Is there a way we can prevent the signature from moving forward if the alignment is done wrong?

**Comment by mjperez-usgs** [comment]
No. There is no way to tell in programming which side of the frog has been
clicked.

*--*
*Michael Perez | IT Specialist*
*USGS Snake River Field Station*
*(208) 426-5946*
*970 Lusk St.*
*Boise,  ID  83706*
