### ISSUE TITLE
Entry Date Static Frog Information

### ISSUE THREAD

**Issue by kbarmstrong-usgs** [mjperez-usgs/identifrog#33]
The data entry date when entering the static frog information is allowed to be at anytime in the future. Should we change this to only allow an entry date as far as the current date?

**Comment by mjperez-usgs** [comment]
No, because it could change with timezones or time switches (e.g. daylight
savings)

*--*
*Michael Perez | IT Specialist*
*USGS Snake River Field Station*
*(208) 426-5946*
*970 Lusk St.*
*Boise,  ID  83706*
