### ISSUE TITLE
Latitude/Longitude Static Frog Information

### ISSUE THREAD

**Issue by kbarmstrong-usgs** [mjperez-usgs/identifrog#37]
The Latitude and Longitude on the Static Frog Information can be letters as well as special characters. Should we limit this to numbers only?

**Comment by mjperez-usgs** [comment]
Probably should leave it is, because lat/long can be very specific in a way that is not "technically" a number.

Decimal Degrees	    Deg:Min:Sec
Lat:	38.898648N	    38° 53' 55.133" N
Lon:	77.037692W	    77° 02' 15.691" W
