### ISSUE TITLE
File Name of Frog Pictures not displayed in Edit Frog

### ISSUE THREAD

**Issue by kbarmstrong-usgs** [mjperez-usgs/identifrog#9]
The first picture added when editing a frog when right hand clicked shows the file picture name but any pictures added after that will not show the file name. (This adds to the confusion of which pictures have been added to that specific frog already).

**Comment by mjperez-usgs** [comment]
This appears to be due to images that were just added. If you don't save the entry the images are not processed into the database, so once you save and return you will see "Originally entered as...". I will add this to make it work on both.
